apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis-container
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
