apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db
spec:
  selector:
    app: db-container
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
