apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: worker
spec:
  selector:
    app: worker-container
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
