apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poll-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LucasMarsala/eks-training
    path: k8s/poll
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: poll
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
